# admin/config.yml - COMPLETO E ATUALIZADO (Tradução + Organização + Dicas de Ajuda)

locale: 'pt'

backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "products"
    label: "Produtos"
    folder: "_products"
    create: true
    extension: "md"
    format: "frontmatter"
    slug: "{{name}}"
    summary: "{{name}} - R$ {{price}}"

    view_groups:
      - label: Categoria
        field: category

    sortable_fields: ['name', 'dateAdded', 'price']
    sort: "name:asc"

    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "produto.njk"}
      - {label: "ID", name: "id", widget: "uuid", required: true}
      - label: "Produto em Estoque?"
        name: "inStock"
        widget: "boolean"
        default: true
      - {label: "Data de Adição", name: "dateAdded", widget: "datetime"}
      - {label: "Nome do Produto", name: "name", widget: "string"}
      
      # MUDANÇA AQUI: Campo com dica de ajuda
      - label: "Preço Original"
        name: "originalPrice"
        widget: "number"
        value_type: "float"
        hint: "Este é o preço 'de'. Ex: 30.00. Use ponto para os centavos."

      # MUDANÇA AQUI: Campo com dica de ajuda
      - label: "Preço com Desconto"
        name: "price"
        widget: "number"
        value_type: "float"
        hint: "Este é o preço final 'por'. Ex: 22.00. Este é o preço que aparece em destaque no site."
        
      - {label: "Imagem Principal", name: "image", widget: "image"}

      # MUDANÇA AQUI: Campo com valor padrão
      - label: "Categoria"
        name: "category"
        widget: "select"
        default: "roupas"
        options:
          - {label: "Roupas", value: "roupas"}
          - {label: "Maquiagens", value: "maquiagens"}
          - {label: "Acessórios", value: "acessorios"}

      - {label: "Tamanho (Ex: G, 38, P/M. Deixe em branco se não aplicável)", name: "size", widget: "string", required: false}
      - label: "Badge (Opcional)"
        name: "badge"
        widget: "object"
        required: false
        fields:
          - {label: "Texto do Badge (Ex: NOVIDADE, PROMOÇÃO)", name: "text", widget: "string", required: false}
      - {label: "Descrição Completa do Produto", name: "body", widget: "markdown"}
