backend:
  name: git-gateway
  branch: main # ou master

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  # ===================================================================
  # INÍCIO DO NOVO CÓDIGO - CONTROLE DOS POPUPS
  # ===================================================================
  - name: "popups"
    label: "Controle dos Popups"
    files:
      - file: "_data/popups.yml"
        label: "Configurações dos Popups"
        name: "popup_controls"
        fields:
          # --- GRUPO 1: POPUP DE BOAS-VINDAS ---
          - label: "Popup de Boas-Vindas (Apenas para novos usuários)"
            name: "new_user_popup"
            widget: "object"
            fields:
              - { label: "Ativar este Popup?", name: "active", widget: "boolean", default: true }
              - { label: "Título", name: "title", widget: "string", default: "Um presente para você!" }
              - { label: "Descrição", name: "description", widget: "markdown", default: "É sua primeira vez aqui? Ganhe **5% de desconto** no seu primeiro pedido!" }
              - { label: "Texto do Botão", name: "button_text", widget: "string", default: "Resgatar Cupom" }
              - { label: "Texto para WhatsApp", name: "whatsapp_text", widget: "string", default: "Olá! Vim pelo site e quero meu cupom de 5% OFF de boas-vindas!" }

          # --- GRUPO 2: POPUP PROMOCIONAL ---
          - label: "Popup Promocional (Editável)"
            name: "promo_popup"
            widget: "object"
            fields:
              - { label: "Ativar este Popup?", name: "active", widget: "boolean", default: false }
              - label: "Como este popup deve aparecer?"
                name: "display_behavior"
                widget: "select"
                options:
                  - { label: "Sempre (para todos os usuários)", value: "always" }
                  - { label: "Apenas uma vez (para todos os usuários)", value: "once" }
                default: "always"
              - { label: "Título", name: "title", widget: "string", default: "Promoção da Semana!" }
              - { label: "Descrição", name: "description", widget: "markdown", default: "Confira nossas ofertas especiais!" }
              - { label: "Texto do Botão", name: "button_text", widget: "string", default: "Ver Ofertas" }
              - { label: "Link do Botão (ex: #categorias ou https://...)", name: "button_link", widget: "string", default: "#categorias" }
  # ===================================================================
  # FIM DO NOVO CÓDIGO
  # ===================================================================

  # Sua coleção de produtos continua aqui normalmente
  - name: "products"
    label: "Produtos"
    folder: "_products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nome do Produto", name: "name", widget: "string" }
      - { label: "Preço Original (Ex: 59.90)", name: "originalPrice", widget: "number" }
      - { label: "Preço com Desconto (Ex: 49.90)", name: "price", widget: "number" }
      - { label: "Data de Adição", name: "dateAdded", widget: "datetime" }
      - { label: "Categoria", name: "category", widget: "select", options: ["roupas", "maquiagens", "acessorios"] }
      - { label: "Imagem Principal", name: "image", widget: "image" }
      - { label: "Descrição (aparece no modal)", name: "body", widget: "markdown", required: false }
      - { label: "Tamanho", name: "size", widget: "string", required: false }
      - label: "Destaque (opcional)"
        name: "badge"
        widget: "object"
        required: false
        fields:
          - { label: "Texto do Destaque (Ex: 'MAIS VENDIDO')", name: "text", widget: "string" }
      - { label: "Em Estoque", name: "inStock", widget: "boolean", default: true }
