# ===================================================================
# ARQUIVO admin/config.yml - BASEADO NA SUA VERSÃO FUNCIONAL
# ===================================================================
backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "products"
    label: "Produtos"
    # VOLTANDO PARA A PASTA CORRETA:
    folder: "_products"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "produto.njk"}
      
      # USANDO A SOLUÇÃO ORIGINAL E CORRETA PARA O ID:
      - {label: "ID", name: "id", widget: "uuid", required: true}

      - {label: "Data de Adição", name: "dateAdded", widget: "datetime"}
      - {label: "Nome do Produto", name: "name", widget: "string"}
      - {label: "Preço Original (Ex: 30.00)", name: "originalPrice", widget: "number", value_type: "float"}
      - {label: "Preço com Desconto (Ex: 22.00)", name: "price", widget: "number", value_type: "float"}
      - {label: "Imagem Principal", name: "image", widget: "image"}
      - label: "Categoria"
        name: "category"
        widget: "select"
        options:
          - {label: "Roupas", value: "roupas"}
          - {label: "Maquiagens", value: "maquiagens"}
          - {label: "Acessórios", value: "acessorios"}
      - {label: "Tamanho (Ex: G, 38, P/M. Deixe em branco se não aplicável)", name: "size", widget: "string", required: false}
      - label: "Badge (Opcional)"
        name: "badge"
        widget: "object"
        required: false
        fields:
          - {label: "Texto do Badge (Ex: NOVIDADE, PROMOÇÃO)", name: "text", widget: "string", required: false}
      - {label: "Descrição Completa do Produto", name: "body", widget: "markdown"}
