# admin/config.yml - VERSÃO FINAL (Tradução, Organização e Dicas em todos os campos)

locale: 'pt'

backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "products"
    label: "Produtos"
    folder: "_products"
    create: true
    extension: "md"
    format: "frontmatter"
    slug: "{{name}}"
    summary: "{{name}} - R$ {{price}}"

    view_groups:
      - label: Categoria
        field: category

    sortable_fields: ['name', 'dateAdded', 'price']
    sort: "name:asc"

    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "produto.njk"}
      - {label: "ID", name: "id", widget: "uuid", required: true}
      - label: "Produto em Estoque?"
        name: "inStock"
        widget: "boolean"
        default: true
      - {label: "Data de Adição", name: "dateAdded", widget: "datetime"}

      # Campo com dica
      - label: "Nome do Produto"
        name: "name"
        widget: "string"
        hint: "Seja descritivo. Ex: Blusa de Tricot Gola Alta Bege"

      # Campo com dica
      - label: "Preço Original"
        name: "originalPrice"
        widget: "number"
        value_type: "float"
        hint: "Este é o preço 'de'. Ex: 30.00. Use ponto para os centavos. Deixe em branco se não houver desconto."
        required: false

      # Campo com dica
      - label: "Preço Final (com desconto)"
        name: "price"
        widget: "number"
        value_type: "float"
        hint: "Este é o preço 'por'. Ex: 22.00. Este é o preço que aparece em destaque no site."

      # Campo com dica
      - label: "Imagem Principal"
        name: "image"
        widget: "image"
        hint: "Clique para escolher uma imagem. Prefira imagens quadradas (Ex: 800x800 pixels) para melhor visualização."

      # Campo com valor padrão
      - label: "Categoria"
        name: "category"
        widget: "select"
        default: "roupas"
        options:
          - {label: "Roupas", value: "roupas"}
          - {label: "Maquiagens", value: "maquiagens"}
          - {label: "Acessórios", value: "acessorios"}

      # Campo com dica no label
      - {label: "Tamanho (Ex: G, 38, P/M. Deixe em branco se não aplicável)", name: "size", widget: "string", required: false}
      
      # Campo com dica interna
      - label: "Badge (Opcional)"
        name: "badge"
        widget: "object"
        required: false
        fields:
          - label: "Texto do Badge"
            name: "text"
            widget: "string"
            required: false
            hint: "Use textos curtos e chamativos. Ex: 'Promoção', 'Novidade', 'Últimas Peças'."
      
      # Campo com dica
      - label: "Descrição Completa do Produto"
        name: "body"
        widget: "markdown"
        hint: "Escreva uma descrição detalhada. Você pode usar **negrito** e *itálico* para destacar informações."
