# Configurações de tradução e personalização
locale: 'pt' 
logo_url: https://i.postimg.cc/ZqP5v2Cj/ES-2.png 
site_url: https://estilocichicsite.netlify.app/ 

backend:
  name: git-gateway
  branch: main 

media_folder: "assets/uploads" 
public_folder: "/assets/uploads"

collections:
  - name: "products"
    label: "Produtos" 
    folder: "_products" 
    create: true 
    slug: "{{name}}" 
    fields: 
      - { label: "ID do Produto", name: "id", widget: "string" }
      - { label: "Nome do Produto", name: "name", widget: "string" }
      - { label: "Preço", name: "price", widget: "number", value_type: "float" }
      - { label: "Preço Original (riscado)", name: "originalPrice", widget: "number", value_type: "float" }
      - { label: "Imagem", name: "image", widget: "image" }
      - { label: "Categoria", name: "category", widget: "select", options: ["roupas", "maquiagens", "acessorios"] }
      - { label: "Tamanho", name: "size", widget: "string", required: false }
      - { label: "Selo (Ex: Novidade)", name: "badge", widget: "object", required: false, fields: [{ label: "Texto do Selo", name: "text", widget: "string" }] }
      - { label: "Descrição", name: "description", widget: "text", required: false }
      - { label: "Data de Adição", name: "dateAdded", widget: "datetime" }