backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "products"
    label: "Produtos"
    folder: "produtos"
    create: true
    fields:
      - {label: "Nome do Produto", name: "name", widget: "string"}
      - {label: "Descrição", name: "body", widget: "markdown"}
