backend:
  name: git-gateway
  branch: main # Ou a branch que você usa, geralmente 'main' ou 'master'

media_folder: "assets/uploads" # Pasta onde as imagens serão salvas
public_folder: "/assets/uploads" # Caminho público para as imagens

collections:
  - name: "products"
    label: "Produtos"
    folder: "_products"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "produto.njk" }
      # ===================================================================
      # A LINHA ABAIXO É A CORREÇÃO. ELA CRIA UM ID ÚNICO E AUTOMÁTICO
      # ===================================================================
      - { label: "ID", name: "id", widget: "uuid" }
      - { label: "Data de Adição", name: "dateAdded", widget: "hidden", default: "{{now}}" }
      - { label: "Nome do Produto", name: "name", widget: "string" }
      - { label: "Preço Original (Ex: 30.00)", name: "originalPrice", widget: "number", value_type: "float" }
      - { label: "Preço com Desconto (Ex: 22.00)", name: "price", widget: "number", value_type: "float" }
      - { label: "Imagem Principal", name: "image", widget: "image" }
      - { label: "Categoria", name: "category", widget: "select", options: ["roupas", "maquiagens", "acessorios"] }
      - { label: "Tamanho (Ex: G, 38, P/M. Deixe em branco se não aplicável)", name: "size", widget: "string", required: false }
      - label: "Badge (Opcional)"
        name: "badge"
        widget: "object"
        required: false
        fields:
          - { label: "Texto do Badge (Ex: NOVIDADE, PROMOÇÃO)", name: "text", widget: "string" }
      - { label: "Descrição Completa do Produto", name: "body", widget: "markdown" }
