locale: 'pt'
backend:
  name: git-gateway
  branch: main
media_folder: "assets/uploads"
public_folder: "/assets/uploads"
collections:
  - label: "Configurações de Pop-ups"
    name: "settings"
    files:
      - label: "Gerenciar Pop-ups"
        name: "popups"
        file: "_data/settings.yml"
        fields:
          - label: "Popup de Boas-Vindas (Aparece 1 vez para novos usuários)"
            name: "welcomeCoupon"
            widget: "object"
            fields:
              - {label: "Ativar este Popup?", name: "active", widget: "boolean", default: true}
              - {label: "Título", name: "title", widget: "string"}
              - {label: "Descrição", name: "description", widget: "markdown"}
              - {label: "Texto do Botão", name: "buttonText", widget: "string"}
              # --- CAMPO ATUALIZADO ---
              - {label: "Mensagem para o WhatsApp", name: "whatsappMessage", widget: "string", hint: "Escreva a mensagem que o cliente enviará. Ex: Olá! Quero meu cupom de 10%!"}

          - label: "Popup de Cupom Geral (Aparece sempre para todos)"
            name: "persistentCoupon"
            widget: "object"
            fields:
              - {label: "Ativar este Popup?", name: "active", widget: "boolean", default: true}
              - {label: "Título", name: "title", widget: "string"}
              - {label: "Descrição", name: "description", widget: "markdown"}
              - {label: "Texto do Botão", name: "buttonText", widget: "string"}
              - {label: "Código do Cupom (Ex: PROMO10)", name: "code", widget: "string"}

  - name: "products"
    label: "Produtos"
    folder: "_products"
    create: true
    extension: "md"
    format: "frontmatter"
    slug: "{{name}}"
    summary: "{{name}} - R$ {{price}} ({{category}})"
    view_groups:
      - {label: Categoria, field: category}
    sortable_fields: ['name', 'dateAdded', 'price']
    sort: "name:asc"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "produto.njk"}
      - {label: "ID", name: "id", widget: "uuid", required: true}
      - {label: "Produto em Estoque?", name: "inStock", widget: "boolean", default: true}
      - {label: "Data de Adição", name: "dateAdded", widget: "datetime"}
      - {label: "Nome do Produto", name: "name", widget: "string"}
      - {label: "Preço Original (Ex: 30.00)", name: "originalPrice", widget: "number", value_type: "float"}
      - {label: "Preço com Desconto (Ex: 22.00)", name: "price", widget: "number", value_type: "float"}
      - {label: "Imagem Principal", name: "image", widget: "image"}
      - label: "Categoria"
        name: "category"
        widget: "select"
        options:
          - {label: "Roupas", value: "roupas"}
          - {label: "Maquiagens", value: "maquiagens"}
          - {label: "Acessórios", value: "acessorios"}
      - {label: "Tamanho", name: "size", widget: "string", required: false}
      - label: "Badge (Opcional)"
        name: "badge"
        widget: "object"
        required: false
        fields:
          - {label: "Texto do Badge", name: "text", widget: "string", required: false}
      - {label: "Descrição Completa", name: "body", widget: "markdown"}

